[package]
name = "lunatic-plugin-sdk"
version = "0.13.2"
edition = "2024"
rust-version = "1.85"
description = "SDK for building lunatic runtime plugins"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = { workspace = true }
